# Generated by Django 4.1.1 on 2022-10-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='passowrd',
            new_name='password',
        ),
    ]
