# Generated by Django 4.1.1 on 2022-10-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_address_order_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
